<a-entity>
  <a-box
    class="interactable"
    id="movableBox"
    position="2.5 1 -37.5"
    width="0.3"
    height="0.3"
    depth="0.3"
    color="red"
    dynamic-body="mass: 5"
    data-valeur="1"
  ></a-box>
</a-entity>
<a-entity>
  <a-box
    class="interactable"
    id="movableBox"
    position="3 1 -37.5"
    width="0.3"
    height="0.3"
    depth="0.3"
    color="green"
    dynamic-body="mass: 5"
    data-valeur="2"
  ></a-box>
</a-entity>
<a-entity>
  <a-box
    class="interactable"
    id="movableBox"
    position="3.5 1 -37.5"
    width="0.3"
    height="0.3"
    depth="0.3"
    color="blue"
    dynamic-body="mass: 5"
    data-valeur="3"
  ></a-box>
</a-entity>
<a-entity>
  <a-box
    class="interactable"
    id="movableBox"
    position="4 1 -37.5"
    width="0.3"
    height="0.3"
    depth="0.3"
    color="magenta"
    dynamic-body="mass: 5"
    data-valeur="4"
  ></a-box>
</a-entity>

<a-entity id="hollowBox" position="-0.9 0.1 -37.5" data-valeur="1">
  <a-box
    position="0 0 0"
    width="0.8"
    height="0.1"
    depth="0.8"
    color="red"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0 0.35 0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="red"
    static-body
    opacity="0.3"
  ></a-box>
  <a-box
    position="0 0.35 -0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="red"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="red"
  ></a-box>
  <a-box
    position="-0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="red"
  ></a-box>
</a-entity>
<a-entity id="hollowBox" position="0 0.1 -37.5" data-valeur="2">
  <a-box
    position="0 0 0"
    width="0.8"
    height="0.1"
    depth="0.8"
    color="green"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0 0.35 0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="green"
    static-body
    opacity="0.3"
  ></a-box>
  <a-box
    position="0 0.35 -0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="green"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="green"
  ></a-box>
  <a-box
    position="-0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="green"
  ></a-box>
</a-entity>
<a-entity id="hollowBox" position="0.9 0.1 -37.5" data-valeur="3">
  <a-box
    position="0 0 0"
    width="0.8"
    height="0.1"
    depth="0.8"
    color="blue"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0 0.35 0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="blue"
    static-body
    opacity="0.3"
  ></a-box>
  <a-box
    position="0 0.35 -0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="blue"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="blue"
  ></a-box>
  <a-box
    position="-0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="blue"
  ></a-box>
</a-entity>
<a-entity id="hollowBox" position="1.8 0.1 -37.5" data-valeur="4">
  <a-box
    position="0 0 0"
    width="0.8"
    height="0.1"
    depth="0.8"
    color="magenta"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0 0.35 0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="magenta"
    static-body
    opacity="0.3"
  ></a-box>
  <a-box
    position="0 0.35 -0.35"
    width="0.8"
    height="0.8"
    depth="0.1"
    color="magenta"
    opacity="0.3"
    static-body
  ></a-box>
  <a-box
    position="0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="magenta"
  ></a-box>
  <a-box
    position="-0.35 0.35 0"
    width="0.1"
    height="0.8"
    depth="0.8"
    opacity="0.3"
    static-body
    color="magenta"
  ></a-box>
</a-entity>
