<a-entity id="scoreboard" position="-8 0.3 -36.5" rotation="0 90 0">
<a-text
  align="center"
  scale="2 2 2"
  value="Leaderboard"
  color="#FFF"
  position="1 6 0.1"
></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="1. {{user1}}"
    color="#FFF"
    position="0.1 5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score1}}"
    color="#FFF"
    position="2 5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="2. {{user2}}"
    color="#FFF"
    position="0.1 4.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score2}}"
    color="#FFF"
    position="2 4.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="3. {{user3}}"
    color="#FFF"
    position="0.1 4 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score3}}"
    color="#FFF"
    position="2 4 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="4. {{user4}}"
    color="#FFF"
    position="0.1 3.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score4}}"
    color="#FFF"
    position="2 3.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="5. {{user5}}"
    color="#FFF"
    position="0.1 3 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score5}}"
    color="#FFF"
    position="2 3 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="6. {{user6}}"
    color="#FFF"
    position="0.1 2.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score6}}"
    color="#FFF"
    position="2 2.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="7. {{user7}}"
    color="#FFF"
    position="0.1 2 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score7}}"
    color="#FFF"
    position="2 2 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="8. {{user8}}"
    color="#FFF"
    position="0.1 1.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score8}}"
    color="#FFF"
    position="2 1.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="9. {{user9}}"
    color="#FFF"
    position="0.1 1 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score9}}"
    color="#FFF"
    position="2 1 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="10. {{user10}}"
    color="#FFF"
    position="0.1 0.5 0.1"
  ></a-text>
  <a-text
    align="center"
    scale="1.4 1.4 1.4"
    value="{{score10}}"
    color="#FFF"
    position="2 0.5 0.1"
  ></a-text>
</a-entity>
