<a-entity id="keyboard" position="1.3 1 -37" rotation="-20 0 0">
        <!-- Row 1 -->
        <a-box position="-1.5 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="Q" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-1.2 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="W" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.9 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="E" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.6 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="R" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.3 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="T" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="Y" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.3 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="U" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.6 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="I" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.9 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="O" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="1.2 0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="P" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>

        <!-- Row 2 -->
        <a-box position="-1.35 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="A" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-1.05 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="S" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.75 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="D" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.45 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="F" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.15 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="G" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.15 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="H" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.45 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="J" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.75 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="K" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="1.05 0 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="L" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>

        <!-- Row 3 -->
        <a-box position="-1.2 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="Z" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.9 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="X" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.6 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="C" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="-0.3 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="V" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="B" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.3 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="N" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box position="0.6 -0.3 0" width="0.25" height="0.25" depth="0.2" class="interactable">
          <a-text value="M" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box color="#FF662F" position="1 -0.3 0" width="0.3" height="0.25" depth="0.2" class="interactable">
          <a-text value="Del" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
        <a-box color="#A3E447" position="1.4 -0.3 0" width="0.3" height="0.25" depth="0.2" class="interactable">
          <a-text value="OK" align="center" position="0 0 0.1" color="#000" scale="0.8 0.8 0.8"></a-text>
        </a-box>
      </a-entity>
      